name: Java GitHub-hosted Workflows

# Quando ocorrer um push ou pull_request na branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Executa um job que:
jobs:
  build:
    # Cria um ambiente Ubuntu para rodar o job
    runs-on: ubuntu-latest

    # e executa os passos abaixo:
    steps:
      # Faz o checkout do código do repositório para o ambiente da ação
      # (baixa o código do repositório GitHub para o ambiente da ação)
      - name: Checkout de código
        uses: actions/checkout@v3

      # Configura o java no ambiente
      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

        # Faz o build do projeto
      - name: Build com Maven
        run: mvn clean install

        # Executa os testes
      - name: Executar testes
        run: mvn test